# Default values for simulation-console.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

zapproxy:
  image: ghcr.io/zaproxy/zaproxy:stable
  name: zapproxy

imagePrefix: ""   # blank by default

consoleui:
  image: "{{ .Values.imagePrefix }}console-ui:latest"
  name: console-ui
  contrastApiToken: "default-token"
  contrastUniqName: "default"
  contrastApiKey: "default-api-key"
  contrastApiAuthorization: "default-authorization"

exploitserver:
  image: "{{ .Values.imagePrefix }}exploit-server:latest"
  name: exploit-server

contrastdatacollector:
  image: "{{ .Values.imagePrefix }}contrastdatacollector:latest"
  name: contrastdatacollector
  contrastUniqName: "default"
  contrastApiToken: "default-token"
  contrastApiKey: "default-api-key"
  contrastApiAuthorization: "default-authorization"
