# Default values for simulation-console.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

zapproxy:
  image: ghcr.io/zaproxy/zaproxy:stable
  name: zapproxy

serviceAccount:
  create: false    # Helm will create a ServiceAccount if true
  name: ""        # optional override; blank means use default fullname

imagePrefix: ""   # blank by default

imagePullPolicy: Never

consoleui:
  image: console-ui:latest
  name: console-ui
  contrastApiToken: "default-token"
  contrastUniqName: "default"
  contrastApiKey: "default-api-key"
  contrastApiAuthorization: "default-authorization"
  vulnAppUrl: "http://cargocats.localhost"       # default for Docker Desktop
  opensearchUrl: "http://opensearch.localhost"   # default for Docker Desktop

exploitserver:
  image: exploit-server:latest
  name: exploit-server

contrastdatacollector:
  image: contrastdatacollector:latest
  name: contrastdatacollector
  contrastUniqName: "default"
  contrastApiToken: "default-token"
  contrastApiKey: "default-api-key"
  contrastApiAuthorization: "default-authorization"